ConvivaMetadata: Update type to handle custom tags with numbers
Conviva/conviva-js-coresdk pull request #2
Opened 2022-09-21 13:10 UTC by MarkusAbtion

When you were trying to set eg. ENCODED_FRAMERATE, the type would clash with the custom tags type and you would get an error whether you put a string or a number.

2023-07-28 15:13 UTC, afief approved these changes

2023-07-28 15:14 UTC, afief commented
Hello, I'm also experiencing the same issue.

2023-10-16 15:30 UTC, jorisw commented on conviva-core-sdk.d.ts
> -} & { [key: string]: string }; // Custom tags
I was going to propose:

```ts
export type ConvivaMetadata =
  { [key: string]: string | number } & // Custom tags / generics first
  {
    [ConvivaKeys.IS_LIVE]?:
        | ConvivaConstants['StreamType']['LIVE']
        | ConvivaConstants['StreamType']['UNKNOWN']
        | ConvivaConstants['StreamType']['VOD'];
    [ConvivaKeys.ASSET_NAME]?: string | null;
    [ConvivaKeys.DURATION]?: number | null;
    [ConvivaKeys.PLAYER_NAME]?: string;
    [ConvivaKeys.STREAM_URL]?: string | null;
     [ConvivaKeys.ENCODED_FRAMERATE]?: number | null;
     [ConvivaKeys.VIEWER_ID]?: string | null;
     [ConvivaKeys.DEFAULT_RESOURCE]?: string | null;
 }
```

2023-10-16 15:30 UTC, jorisw commented
@kedarmarsada Please review this year-old PR.

2023-10-16 15:34 UTC, jorisw commented
@shansmuhammad Please review this year-old PR. Thanks.

2023-10-16 15:36 UTC, jorisw commented on conviva-core-sdk.d.ts
> -} & { [key: string]: string }; // Custom tags
... as it appears now that having the `& { [key: string]: string }` at the end, is undoing everything before it.

2023-10-17 11:55 UTC, jorisw approved these changes

2023-10-17 12:28 UTC, shansmuhammad commented on conviva-core-sdk.d.ts
> -} & { [key: string]: string }; // Custom tags
Hi @jorisw , The particular API only accepts the string inputs.

so please convert or stringify your data and provide the value as parameter.

2023-10-17 12:30 UTC, shansmuhammad requested changes
Please Stringify the input parameter and give as the input value.

2023-10-17 12:33 UTC, MarkusAbtion commented
@shansmuhammad The issue is that the ENCODED_FRAMERATE is expecting a number.
So if you try to set it, you get the following error:
```
Type '{ "Conviva.encodedFrameRate": number; }' is not assignable to type 'ConvivaMetadata'.
  Type '{ "Conviva.encodedFrameRate": number; }' is not assignable to type '{ [key: string]: string; }'.
    Property '[ConvivaKeys.ENCODED_FRAMERATE]' is incompatible with index signature.
      Type 'number' is not assignable to type 'string'.ts(2322)
```

2023-10-17 12:34 UTC, MarkusAbtion commented
And if I stringify the number, I get:
```
Type of computed property's value is 'string', which is not assignable to type 'number'.ts(2418)
conviva-core-sdk.ts(189, 5): The expected type comes from property 'Conviva.encodedFrameRate' which is declared here on type 'ConvivaMetadata'
```

2023-10-17 12:47 UTC, shansmuhammad reviewed
Can you please try to convert the number, we are trying to generalise the API to take string value, inside the string it can be any type.

Can you try to put like "1234"

2023-10-17 12:58 UTC, MarkusAbtion commented
That's what I did here:

> And if I stringify the number, I get:
> 
> ```
> Type of computed property's value is 'string', which is not assignable to type 'number'.ts(2418)
> conviva-core-sdk.ts(189, 5): The expected type comes from property 'Conviva.encodedFrameRate' which is declared here on type 'ConvivaMetadata'
> ```

2023-10-17 12:59 UTC, MarkusAbtion commented
```ts
// None of these work
const metadataWithStringFramerate: ConvivaMetaData = {
  [ConvivaKeys.ENCODED_FRAMERATE]: "123"
}

const metadataWithNumberFramerate: ConvivaMetaData = {
  [ConvivaKeys.ENCODED_FRAMERATE]: 123
}
```

2023-10-17 13:01 UTC, shansmuhammad reviewed
Ok got it, please allow to check further

We will get back to you

2023-10-17 13:03 UTC, shansmuhammad reviewed
This files have been generated from a different repo.

Let me check those and we will get back to you.

2024-07-26 10:10 UTC, kedarmarsada commented
Changes are taken care in subsequent releases

2024-07-26 10:10 UTC, closed without merging